trigger:
- main

pool:
  name: Default   # self-hosted agent pool where RAYAN is online

steps:
# استخدم بايثون 3.10 (إن كان متوفر على الوكيل)
- task: UsePythonVersion@0
  displayName: "Set Python 3.10"
  inputs:
    versionSpec: '3.10'

# ========== Install ==========
- task: PowerShell@2
  displayName: "Install dependencies"
  inputs:
    targetType: 'inline'
    script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

# ========== Lint ==========
- task: PowerShell@2
  displayName: "Lint"
  inputs:
    targetType: 'inline'
    script: |
      python -m pylint --disable=R,C hello.py

# ========== Test ==========
- task: PowerShell@2
  displayName: "Test"
  inputs:
    targetType: 'inline'
    script: |
      python -m pytest -vv test_hello.py

# ========== Archive (zip) ==========
- task: ArchiveFiles@2
  displayName: "Archive app"
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

# ========== Deploy ==========
- task: AzureWebApp@1
  displayName: "Deploy to Azure Web App"
  inputs:
    azureSubscription: 'AZURE_SP_CONNECTION'
    appName: 'rayan-ci-cd-app-we'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'

